-- Tworzenie użytkownika dla aplikacji
CREATE USER ApplicationIdentity WITH PASSWORD 'gGaaFEeAZg9nNfQk';

GRANT CONNECT ON DATABASE projekt TO ApplicationIdentity;
GRANT USAGE ON SCHEMA public TO ApplicationIdentity;

-- CRUD
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO ApplicationIdentity;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO ApplicationIdentity;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO ApplicationIdentity;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE
ON SEQUENCES TO ApplicationIdentity;